config/routes.rb
Rails.application.routes.draw do
  resources :mpesas
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :admins, controllers: { 
    registrations: 'workers/registrations',
    sessions: 'workers/sessions'
 }
  devise_for :workers, controllers: { 
    registrations: 'workers/registrations',
    sessions: 'workers/sessions'
 }
  
  resources :inventories
  resources :services
  resources :bookings

  root "home#index"

  post 'stkpush', to: 'mpesas#stkpush'
  post 'stkquery', to: 'mpesas#stkquery'
  post 'pay', to: 'mpesas#pay'
  get "up" => "rails/health#show", as: :rails_health_check
  get "home" => "home#index"
  get "worker" => "worker_dashboard#index"
end

app/views/layouts/_service_bookings_chart.html.erb
<!-- app/views/admin/dashboard/_service_bookings_chart.html.erb -->
<div class="chart-container" style="position: relative; height:40vh; width:80vw">
  <canvas id="serviceBookingsChart"></canvas>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var ctx = document.getElementById('serviceBookingsChart').getContext('2d');
    var serviceBookingsChart = new Chart(ctx, {
      type: 'bar',
      data: {
        labels: <%= Service.pluck(:name).to_json.html_safe %>,
        datasets: [{
          label: 'Number of Bookings',
          data: <%= Service.joins(:booking_histories).group(:name).count.values.to_json.html_safe %>,
          backgroundColor: 'rgba(75, 192, 192, 0.2)',
          borderColor: 'rgba(75, 192, 192, 1)',
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
  });
</script>

app/views/layouts/_worker_commissions_chart.html.erb
<!-- app/views/admin/dashboard/_worker_commissions_chart.html.erb -->
<div class="chart-container" style="position: relative; height:40vh; width:80vw">
  <canvas id="workerCommissionsChart"></canvas>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var ctx = document.getElementById('workerCommissionsChart').getContext('2d');
    var workerCommissionsChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: <%= Worker.pluck(:name).to_json.html_safe %>,
        datasets: [{
          label: 'Total Commission',
          data: <%= Worker.joins(:worker_commissions).group(:name).sum(:commission).values.to_json.html_safe %>,
          backgroundColor: 'rgba(153, 102, 255, 0.2)',
          borderColor: 'rgba(153, 102, 255, 1)',
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pos</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag 'password_toggle' %>
  <%= javascript_importmap_tags %>

  <style>
    /* Custom CSS for hamburger menu */
    .menu-toggle {
      display: none; /* Hide the hamburger menu by default */
    }

    @media (max-width: 640px) { /* Show the hamburger menu on small screens */
      .menu-toggle {
        display: block;
      }
      /* .nav-items {
        display: none; /* Hide the navigation items by default on small screens */
   
      .nav-open .nav-items {
        display: block; /* Show the navigation items when the nav-open class is applied */
      }
    }
    /* Additional styles for checkbox selection */
    .checkbox-selected {
      background-color: green; /* Light green background for selected checkboxes */
    }

  </style>
</head>

<body class="bg-gray-100">
  <!-- Hamburger menu button -->
  <%# <button class="menu-toggle sm:hidden absolute top-4 right-4 p-4 text-white">
    <svg class="w-6 h-6 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
      <path class="menu-icon" fill-rule="evenodd" d="M3 18h18v-2H3v2zM3 13h18v-2H3v2zM3 6v2h18V6H3z"/>
    </svg>
  </button> %>

  <!-- Navigation bar -->
  <nav class="p-4 nav-items">
    <ul class="flex flex-row sm:flex-row  justify-evenly">
      <% if worker_signed_in? %>
        <li>
          <%= link_to 'Worker Dashboard', worker_path, class: "bg-yellow-500 text-black hover:bg-yellow-600 font-semibold py-2 px-4 rounded shadow" %>
        </li>
        <li>
          <%= link_to 'Edit Profile', edit_worker_registration_path, class: "bg-blue-500 text-white hover:bg-blue-600 font-semibold py-2 px-4 rounded shadow" %>
        </li>
        <li>
          <%= button_to 'Logout', destroy_worker_session_path, method: :delete, class: "bg-red-500 text-white hover:bg-red-600 font-semibold py-2 px-4 rounded shadow" %>
        </li>
      <% elsif admin_signed_in? %>
        <li>
          <%= link_to "Admin Panel", home_admin_path, class: "bg-blue-500 text-white hover:bg-blue-600 font-semibold py-2 px-4 rounded shadow" %>
        </li>

        <li>
          <%= link_to "Edit Profile", edit_admin_registration_path, class: "bg-blue-500 text-white hover:bg-blue-600 font-semibold py-2 px-4 rounded shadow" %>
        </li>

        <li>
          <%= button_to 'Logout', destroy_admin_session_path, method: :delete, class: "bg-red-500 text-white hover:bg-red-600 font-semibold py-2 px-4 rounded shadow" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Check booked session", bookings_path, class: "bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-2 px-4 rounded transition-colors duration-300" %>
        </li>
      <% end %>
      <li>
        <%= link_to 'Home', home_path, class: "bg-green-500  hover:bg-green-600 font-semibold py-2 px-4 rounded shadow" %>
      </li>
    </ul>
  </nav>

  <div class="container mx-auto p-4">
    <% if notice.present? %>
      <p class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative mb-4" role="alert">
        <span class="block sm:inline"><%= notice %></span>
      </p>
    <% end %>

    <% if alert.present? %>
      <p class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4" role="alert">
        <span class="block sm:inline"><%= alert %></span>
      </p>
    <% end %>

    <%= yield %>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.8.3/anime.min.js"></script>
  <script>
    const menuToggle = document.querySelector('.menu-toggle');
    const navItems = document.querySelector('.nav-items');

      menuToggle.addEventListener('click', () => {
        if (navItems.style.display === 'none') {
          navItems.style.display = 'block';
        } else {
          navItems.style.display = 'none';
        }
      });
    document.addEventListener('DOMContentLoaded', function () {
      const checkboxes = document.querySelectorAll('input[type="checkbox"]');
      checkboxes.forEach(checkbox => {
        checkbox.addEventListener('change', () => {
          if (checkbox.checked) {
            checkbox.parentElement.classList.add('checkbox-selected');
          } else {
            checkbox.parentElement.classList.remove('checkbox-selected');
          }
        });
      });
    });
  </script>
</body>
</html>